### ISSUE TITLE
Satdump 1.2.1 Android app crash ADB Log Attached

### ISSUE THREAD

**Issue by benb0jangles** [SatDump/SatDump#871] opened 2024-11-21 00:38 UTC
### Satdump Android APK v1.2.1 - App crashes during startup

I try Satdump android .apk v1.1.4 - v1.2.1 all versions crash at startup
But Satdump android apk v1.1.3 is working but no good to me as I am trying to use dvb-s & dvb-s2 for datv

**Device info:**
Android 12 
Arm64
8GB Ram

**App version:**
Satdump android APK v1.2.1

**Crash Log:**
`benji@Benjis-Mac-mini ~ % adb logcat --buffer=crash                 
--------- beginning of crash
11-20 23:20:06.442 18116 18116 F DEBUG   : Diagnostic-Collection-Type: Tombstone Proto
11-20 23:20:06.442 18116 18116 F DEBUG   : Has-Diagnostic-Summary: Yes
11-20 23:20:06.442 18116 18116 F DEBUG   : APK-Location: /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/base.apk
11-20 23:20:06.442 18116 18116 F DEBUG   : Debugging: No
11-20 23:20:06.442 18116 18116 F DEBUG   : Has-Waited-For-Debugger: No
11-20 23:20:06.442 18116 18116 F DEBUG   : Last-Activity-Time: 1259375
11-20 23:20:06.442 18116 18116 F DEBUG   : Process-Runtime: 749
11-20 23:20:06.442 18116 18116 F DEBUG   : Waiting-To-Kill: 
11-20 23:20:06.442 18116 18116 F DEBUG   : Killed-By-AM: No
11-20 23:20:06.442 18116 18116 F DEBUG   : Removed: No
11-20 23:20:06.442 18116 18116 F DEBUG   : Wanted-ANR-Ui: No
11-20 23:20:06.442 18116 18116 F DEBUG   : Killed: No
11-20 23:20:06.442 18116 18116 F DEBUG   : OOM-Score-Adj: 1
11-20 23:20:06.442 18116 18116 F DEBUG   : Wanted-Error-Ui: No
11-20 23:20:06.442 18116 18116 F DEBUG   : Kill-Time: 0
11-20 23:20:06.442 18116 18116 F DEBUG   : State: TOP 
11-20 23:20:06.442 18116 18116 F DEBUG   : Foreground: Yes
11-20 23:20:06.442 18116 18116 F DEBUG   : Executable: /system/bin/app_process64
11-20 23:20:06.442 18116 18116 F DEBUG   : Cmdline: org.satdump.SatDump
11-20 23:20:06.442 18116 18116 F DEBUG   : pid: 18071, tid: 18100, name: Thread-4  >>> org.satdump.SatDump <<<
11-20 23:20:06.442 18116 18116 F DEBUG   : uid: 10182
11-20 23:20:06.442 18116 18116 F DEBUG   : tagged_addr_ctrl: 0000000000000001
11-20 23:20:06.442 18116 18116 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-20 23:20:06.442 18116 18116 F DEBUG   : Cause: null pointer dereference
11-20 23:20:06.442 18116 18116 F DEBUG   :     x0  0000007cf09d2908  x1  0000000000000000  x2  0000000000000080  x3  0000000000000004
11-20 23:20:06.442 18116 18116 F DEBUG   :     x4  0000007d05101a23  x5  0000007d02ab223b  x6  000000000000003b  x7  0000007d051019e8
11-20 23:20:06.442 18116 18116 F DEBUG   :     x8  0000000000000000  x9  000000000000007f  x10 00000000000046b4  x11 00000000000046b4
11-20 23:20:06.442 18116 18116 F DEBUG   :     x12 0000000000000000  x13 c949d7c7509e6557  x14 c3a5c85c97cb3127  x15 0000007e3b6f919a
11-20 23:20:06.442 18116 18116 F DEBUG   :     x16 0000007d63125d20  x17 0000007e2f500110  x18 0000007d04fb0000  x19 0000007cf09cbdb0
11-20 23:20:06.442 18116 18116 F DEBUG   :     x20 4744407d6a1affdf  x21 0000007cf09d1e30  x22 0000007cf09cbd58  x23 0000007d05101c40
11-20 23:20:06.442 18116 18116 F DEBUG   :     x24 0000007cf09d1e30  x25 0000007cf09ce604  x26 000000000000002a  x27 0000007cf09d2af8
11-20 23:20:06.442 18116 18116 F DEBUG   :     x28 0000007d05101c40  x29 0000007d051004e0
11-20 23:20:06.442 18116 18116 F DEBUG   :     lr  0000007d630fcfd4  sp  0000007d051004e0  pc  0000007e2f500124  pst 0000000060001000
11-20 23:20:06.442 18116 18116 F DEBUG   : backtrace:
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)00 pc 00000000000cb124  /apex/com.android.runtime/lib64/bionic/libc.so (strlcpy+20) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)01 pc 00000000001f2fd0  /vendor/lib64/libgsl.so (os_strlcpy+8) (BuildId: 086f7d77c12da19a5346f8656fcb129b)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)02 pc 000000000048f254  /vendor/lib64/libCB.so (!!!0000!eaf9457fe520db5e17682dbbf77ed2!5c44054b8b!+716) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)03 pc 000000000048f334  /vendor/lib64/libCB.so (!!!0000!32ec70eb6df5b508bb5e922ca3c0f3!5c44054b8b!+76) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)04 pc 000000000048a1e0  /vendor/lib64/libCB.so (!!!0000!3cee9793d440a49a09777e007c2577!5c44054b8b!+19176) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)05 pc 00000000004afae8  /vendor/lib64/libCB.so (cb_get_platform_info+112) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)06 pc 000000000001a108  /vendor/lib64/libOpenCL_adreno.so (qCLDrvAPI_clGetPlatformInfo+136) (BuildId: 211f89156dc6a60d89db64d8d50e621a)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)07 pc 00000000000073c8  /vendor/lib64/libOpenCL.so (khrIcdVendorAdd+808) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)08 pc 0000000000007ce8  /vendor/lib64/libOpenCL.so (khrIcdVendorsEnumerateEnv+160) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)09 pc 000000000000c1fc  /vendor/lib64/libOpenCL.so (khrIcdOsVendorsEnumerate+12) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)10 pc 00000000000f1770  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_once+128) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)11 pc 0000000000007ff8  /vendor/lib64/libOpenCL.so (clGetPlatformIDs+28) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)12 pc 00000000008b2b4c  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libsatdump_core.so (clGetPlatformIDs+52) (BuildId: fa13c5e9724cc36c2f49e2cfe6f168d08fab05dc)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)13 pc 0000000000600078  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libsatdump_core.so (satdump::opencl::getAllDevices()+76) (BuildId: fa13c5e9724cc36c2f49e2cfe6f168d08fab05dc)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)14 pc 0000000000600914  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libsatdump_core.so (satdump::opencl::resetOCLContext()+616) (BuildId: fa13c5e9724cc36c2f49e2cfe6f168d08fab05dc)
11-20 23:20:06.442 18116 18116 F DEBUG   :       (#)15 pc 0000000000600490  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libsatdump_core.so (satdump::opencl::initOpenCL()+152) (BuildId: fa13c5e9724cc36c2f49e2cfe6f168d08fab05dc)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)16 pc 00000000008475e0  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libsatdump_core.so (satdump::initSatdump(bool)+2304) (BuildId: fa13c5e9724cc36c2f49e2cfe6f168d08fab05dc)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)17 pc 0000000000015d54  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libandroid_imgui.so (init(android_app*)+900) (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)18 pc 0000000000020be8  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libandroid_imgui.so (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)19 pc 0000000000016c20  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libandroid_imgui.so (android_main+228) (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)20 pc 0000000000020ab0  /data/app/~~0XerdQ6EMclxBl5xmvTGEg==/org.satdump.SatDump-cTyPZbj8mMtHqJe579zaUA==/lib/arm64/libandroid_imgui.so (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)21 pc 00000000000efbac  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-20 23:20:06.443 18116 18116 F DEBUG   :       (#)22 pc 000000000008c200  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-20 23:20:06.466 18071 18100 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 18100 (Thread-4), pid 18071 (satdump.SatDump)
11-20 23:20:06.776 18121 18121 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by JVital2013** [comment] 2024-11-21 12:57
Hello! Unfortunately, this looks like a bug in your phone's ROM. What phone and ROM are you running?

Per the stack trace you shared, the standard OpenCL `clGetPlatformIDs()` function is called, but then it crashes within the operating system .so files when trying to complete the call. clGetPlatformIDs is a standard OpenCL call that we're using in the standard way, so I don't think the issue can be within SatDump.

1.1.3 works because we had no support for OpenCL on Android then. OpenCL is not completely supported on Android by Google, but this is the first time we've heard of it causing a problem. You could try building an APK without OpenCL support - you would need to remove this line in cmake: https://github.com/SatDump/SatDump/blob/3e54b34eee7564605cb65cc753042bc7516e9310/CMakeLists.txt#L30

**Comment by benb0jangles** [comment] 2024-11-21 17:12
Hello :)

I can find the gpu data by using grep GLES:
`benji@Benjis-Mac-mini ~ % adb shell dumpsys SurfaceFlinger | grep GLES
GLES: Qualcomm, Adreno (TM) 740, OpenGL ES 3.2 V@0797.0 (GIT@5c44054b8b, I064dd7d485, 1726116466) (Date:09/12/24)
`
Search shows Qualcomm Adreno 740 gpu support: 
OpenGL ES 3.2, Vulkan 1.3 OpenCL 2.0, DirectX 12

I can do adb pull to get libopencl.so:
`adb pull /system/vendor/lib/libOpenCL.so ./`

Attached is link to libopencl.so file:
[libOpenCL.so.zip](https://github.com/user-attachments/files/17849631/libOpenCL.so.zip)

Is it possible you or someone you know has Android Studio setup for .apk compiling? 
I have not setup Android Studio before and have minimal experience with the ide.

**Comment by JVital2013** [comment] 2024-11-21 18:02
I had an idea we can do for troubleshooting: does this app run on your phone: https://play.google.com/store/apps/details?id=de.saschawillems.openclcapsviewer&hl=en_US&pli=1. My guess is, this app will crash in a similar fashion since it loads OpenCL on Android in a similar way to SatDump.

As for building, unfortunately we haven't fully documented the Android build process. You should use Linux, but I've done it on macOS before as well. Here's the overall steps:

1. Download the Android SDK for your operating system from here: https://developer.android.com/studio (under Command Line Tools Only).
2. Configure the SDK as described here: https://github.com/SatDump/Android-Dependencies/blob/b552800c532b117af5722679aa0c9712d0ffc008/build.sh#L4-L18. For macOS you'll need to install OpenJDK some other way
3. export ANDROID_HOME=/path/to/android/sdk
4. git clone SatDump's repository
5. Modify the cmake list to set OPENCL_FOUND to 0 on android
6. cd satdump
7. git submodule update --init
8. cd android/deps
9. sh build.sh
10. cd ..
11. gradle assembleDebug

This will save an APK which you can then install on your phone. You can also do assembleRelease for a faster piece of software, but then you need to mess with signing. Best to stick with assembleDebug for starters.

**Comment by JVital2013** [comment] 2024-11-21 18:08
I should add: if you have trouble building SatDump, don't sweat it. I'd focus on trying the app at https://play.google.com/store/apps/details?id=de.saschawillems.openclcapsviewer&hl=en_US&pli=1 and let me know if that works.

In the meantime, I think I can trap the error and prevent it from causing a crash. I'll let you know once I make some progress.

**Comment by benb0jangles** [comment] 2024-11-21 19:45
Yah openclcapsviewer.apk also crashing

**Comment by JVital2013** [comment] 2024-11-22 00:35
Ok - since other OpenCL apps are also crashing, the issue is definitely with your phone/ROM. The chip should support OpenCL, but there's something wrong with the drivers.

That being said, there's a slight chance I can work around it. Can you please try this specific build to see if it works on your phone: https://github.com/SatDump/SatDump/actions/runs/11963647281/artifacts/2221858657. You will need to download it from a web browser signed into a github account, as I haven't merged this change into the nightly builds yet.

I'm not holding my breath this will work, but it is worth a shot!

**Comment by benb0jangles** [comment] 2024-11-22 02:41
Another crash using specific build. adb debug info:

`Build fingerprint: 'oculus/panther/panther:12/SQ3A.220605.009.A1/393100085900610:user/release-keys'
11-22 02:34:10.048 17556 17556 F DEBUG   : Revision: '0'
11-22 02:34:10.048 17556 17556 F DEBUG   : ABI: 'arm64'
11-22 02:34:10.048 17556 17556 F DEBUG   : Timestamp: 2024-11-22 02:34:09.830012220+0000
11-22 02:34:10.048 17556 17556 F DEBUG   : Process uptime: 1s
11-22 02:34:10.048 17556 17556 F DEBUG   : Diagnostic-Collection-Type: Tombstone Proto
11-22 02:34:10.048 17556 17556 F DEBUG   : Has-Diagnostic-Summary: Yes
11-22 02:34:10.048 17556 17556 F DEBUG   : APK-Location: /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/base.apk
11-22 02:34:10.048 17556 17556 F DEBUG   : Debugging: No
11-22 02:34:10.048 17556 17556 F DEBUG   : Has-Waited-For-Debugger: No
11-22 02:34:10.048 17556 17556 F DEBUG   : Last-Activity-Time: 30615364
11-22 02:34:10.048 17556 17556 F DEBUG   : Process-Runtime: 52952890
11-22 02:34:10.048 17556 17556 F DEBUG   : Waiting-To-Kill: 
11-22 02:34:10.048 17556 17556 F DEBUG   : Killed-By-AM: No
11-22 02:34:10.048 17556 17556 F DEBUG   : Removed: No
11-22 02:34:10.048 17556 17556 F DEBUG   : Wanted-ANR-Ui: No
11-22 02:34:10.048 17556 17556 F DEBUG   : Killed: No
11-22 02:34:10.048 17556 17556 F DEBUG   : OOM-Score-Adj: 1
11-22 02:34:10.048 17556 17556 F DEBUG   : Wanted-Error-Ui: No
11-22 02:34:10.048 17556 17556 F DEBUG   : Kill-Time: 0
11-22 02:34:10.048 17556 17556 F DEBUG   : State: TOP 
11-22 02:34:10.048 17556 17556 F DEBUG   : Foreground: Yes
11-22 02:34:10.048 17556 17556 F DEBUG   : Executable: /system/bin/app_process64
11-22 02:34:10.048 17556 17556 F DEBUG   : Cmdline: org.satdump.SatDump
11-22 02:34:10.048 17556 17556 F DEBUG   : pid: 17513, tid: 17542, name: Thread-4  >>> org.satdump.SatDump <<<
11-22 02:34:10.048 17556 17556 F DEBUG   : uid: 10189
11-22 02:34:10.048 17556 17556 F DEBUG   : tagged_addr_ctrl: 0000000000000001
11-22 02:34:10.048 17556 17556 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-22 02:34:10.048 17556 17556 F DEBUG   : Cause: null pointer dereference
11-22 02:34:10.048 17556 17556 F DEBUG   :     x0  0000007a43bfc908  x1  0000000000000000  x2  0000000000000080  x3  0000000000000004
11-22 02:34:10.048 17556 17556 F DEBUG   :     x4  0000007a5f381a23  x5  0000007a5d728cbb  x6  000000000000003b  x7  0000007a5f3819e8
11-22 02:34:10.048 17556 17556 F DEBUG   :     x8  0000000000000000  x9  000000000000007f  x10 0000000000004486  x11 0000000000004486
11-22 02:34:10.048 17556 17556 F DEBUG   :     x12 0000000000000000  x13 ffe0000000000000  x14 0000000000000001  x15 0000007b93f8319a
11-22 02:34:10.048 17556 17556 F DEBUG   :     x16 0000007ac2351d20  x17 0000007b6b392110  x18 0000007a5f140000  x19 0000007a43bf5db0
11-22 02:34:10.048 17556 17556 F DEBUG   :     x20 ddb545f4701ae961  x21 0000007a43bfbe30  x22 0000007a43bf5d58  x23 0000007a5f381c40
11-22 02:34:10.048 17556 17556 F DEBUG   :     x24 0000007a43bfbe30  x25 0000007a43bf8604  x26 000000000000002a  x27 0000007a43bfcaf8
11-22 02:34:10.048 17556 17556 F DEBUG   :     x28 0000007a5f381c40  x29 0000007a5f380490
11-22 02:34:10.048 17556 17556 F DEBUG   :     lr  0000007ac2328fd4  sp  0000007a5f380490  pc  0000007b6b392124  pst 0000000060001000
11-22 02:34:10.048 17556 17556 F DEBUG   : backtrace:
11-22 02:34:10.048 17556 17556 F DEBUG   :       #00 pc 00000000000cb124  /apex/com.android.runtime/lib64/bionic/libc.so (strlcpy+20) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #01 pc 00000000001f2fd0  /vendor/lib64/libgsl.so (os_strlcpy+8) (BuildId: 086f7d77c12da19a5346f8656fcb129b)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #02 pc 000000000048f254  /vendor/lib64/libCB.so (!!!0000!eaf9457fe520db5e17682dbbf77ed2!5c44054b8b!+716) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #03 pc 000000000048f334  /vendor/lib64/libCB.so (!!!0000!32ec70eb6df5b508bb5e922ca3c0f3!5c44054b8b!+76) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #04 pc 000000000048a1e0  /vendor/lib64/libCB.so (!!!0000!3cee9793d440a49a09777e007c2577!5c44054b8b!+19176) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #05 pc 00000000004afae8  /vendor/lib64/libCB.so (cb_get_platform_info+112) (BuildId: 00b757121cca2dc7e23313ebd79193d3)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #06 pc 000000000001a108  /vendor/lib64/libOpenCL_adreno.so (qCLDrvAPI_clGetPlatformInfo+136) (BuildId: 211f89156dc6a60d89db64d8d50e621a)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #07 pc 00000000000073c8  /vendor/lib64/libOpenCL.so (khrIcdVendorAdd+808) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #08 pc 0000000000007ce8  /vendor/lib64/libOpenCL.so (khrIcdVendorsEnumerateEnv+160) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #09 pc 000000000000c1fc  /vendor/lib64/libOpenCL.so (khrIcdOsVendorsEnumerate+12) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #10 pc 00000000000f1770  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_once+128) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #11 pc 0000000000007ff8  /vendor/lib64/libOpenCL.so (clGetPlatformIDs+28) (BuildId: 2691f3b9b26cb46322a26721d7b72852)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #12 pc 00000000008b2cc4  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libsatdump_core.so (clGetPlatformIDs+52) (BuildId: 78ac8aadd073b5a6d09b27fe8c7f623dea134e2b)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #13 pc 00000000006000d0  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libsatdump_core.so (satdump::opencl::getAllDevices()+76) (BuildId: 78ac8aadd073b5a6d09b27fe8c7f623dea134e2b)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #14 pc 0000000000600b24  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libsatdump_core.so (satdump::opencl::resetOCLContext()+616) (BuildId: 78ac8aadd073b5a6d09b27fe8c7f623dea134e2b)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #15 pc 00000000006006a0  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libsatdump_core.so (satdump::opencl::initOpenCL()+152) (BuildId: 78ac8aadd073b5a6d09b27fe8c7f623dea134e2b)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #16 pc 0000000000847758  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libsatdump_core.so (satdump::initSatdump(bool)+2312) (BuildId: 78ac8aadd073b5a6d09b27fe8c7f623dea134e2b)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #17 pc 0000000000015d54  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libandroid_imgui.so (init(android_app*)+900) (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #18 pc 0000000000020be8  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libandroid_imgui.so (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #19 pc 0000000000016c20  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libandroid_imgui.so (android_main+228) (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #20 pc 0000000000020ab0  /data/app/~~fUO9emZkk63b5EUX2fYLww==/org.satdump.SatDump-weNdRiVf6UU1GvsL0AzbjQ==/lib/arm64/libandroid_imgui.so (BuildId: e1e217b10bd8ec8b16387f9c260a36b8321973b4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #21 pc 00000000000efbac  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-22 02:34:10.048 17556 17556 F DEBUG   :       #22 pc 000000000008c200  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 87ab5f8b3224dc25f4c7bc2bc65c4cf4)
11-22 02:34:10.068 17513 17542 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 17542 (Thread-4), pid 17513 (satdump.SatDump)`

**Closed** 2024-11-22 15:55 UTC
Labels: bug

**Comment by benb0jangles** [comment] 2024-11-22 20:20
Nice result, the no-opencl apk file from google drive link above is working. 

I am able to run satdump dvb-s live decode of a 2GB baseband file, and output the video stream. All on an android phone :)

There is still a bit of work to do:
-the video player is buffering for a couple of minutes before video is displayed, it is relying on software decoding
-I am unable to have the video player use hardware decode for some reason, and I don't know if it will be faster.
-I am wondering what the performance difference of OpenCL vs No_OpenCL on android devide when doing dvb-s demodulation using satdump

I messaged the device vendor today about opencl issues, I will continue to pursue it.

Thanks for your help and assistance, It is exciting to have a rough but functioning dvb-s setup on just an android phone. One day we might be picking up iss datv if they ever get it up and running.

I will also try dvb-s2 soon.

**Comment by JVital2013** [comment] 2024-11-22 23:38
Glad I could help! It's interesting you're unable to have your video player do hardware decode. That very well could be related to your issue.

OpenCL is not used for DVB-S/S2 demodulation. It relies on SIMD operations within the CPU, so there's no performance impact for what you're trying to do. OpenCL is mostly used for projecting satellite imagery.
