### ISSUE TITLE
Bit Depth parameter is not restored as it was selected when saving

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#537] opened 2023-11-29 18:55 UTC
When starting satdump-ui almost all saved parameters are correctly restored with previously saved options and values.
However Bit Depth is back to default 8 bit value although 16 bits was set before saving in Settings.

Bernard, f6bvp

**Comment by JVital2013** [comment] 2023-11-29 19:50
Are you referring to when you use the SatDump SDR Server?

**Comment by f6bvp** [comment] 2023-11-29 20:41
Yes. Sorry, this was not obvious.Parameters are restored in two steps. Some as soon as Satdump-ui is started, others when selecting a device source.Bit depth is not.Dr Bernard Pidoux73 de Bernard, F6BVP-- मेरे बहुत-से शौक़ हैंj'ai beaucoup de passe-tempshttp://radiotelescope-lavillette.frLe 29 nov. 2023 à 20:50, Jamie Vital ***@***.***> a écrit :﻿
Are you referring to when you use the SatDump SDR Server?

**Comment by JVital2013** [comment] 2023-12-15 04:10
Sorry for the delayed response on this one - I can reproduce the issue, and we'll have to look at how to fix it. Right now, it's not designed to save the bit depth in the client - it's expecting the server to send the bit depth to use. The problem is, the server never appears to send the bit depth information (let alone send the last used bit-depth). 

To be investigated!

**Comment by JVital2013** [comment] 2023-12-17 03:56
Quick update - we're still working on this - I got a bit distracted with fixing other bugs in the SDR server first 😄. A quick correction on what I last said: settings are saved client-side, and will be loaded from the saved settings soon!

**Comment by JVital2013** [comment] 2023-12-17 13:48
This is now fixed as of the latest commit. Thanks for the report!

**Closed by JVital2013** 2023-12-17 13:48 UTC
Labels: bug
