### ISSUE TITLE
sdr_remote_support making SATDUMP crash

### ISSUE THREAD

**Issue by YD9CKH** [SatDump/SatDump#682] opened 2024-04-09 12:46 UTC
sdr_remote_support.dll making SATDUMP crash (not responding)

Hardware
- Airspy mini
- Windows 10 Pro 22H2

Satdump version v1.2.0-42471fa

**Comment by JVital2013** [comment] 2024-04-09 15:19
Duplicate of #638. We have a fix in the works; please follow that issue for updates

**Closed by JVital2013** 2024-04-09 15:19 UTC
Labels: bug
